/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as DefinirSenhaRouteImport } from './routes/definir-senha'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as NovaPropostaRouteImport } from './routes/nova-proposta'
import { Route as PropostasRouteImport } from './routes/propostas'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminConteudoRouteImport } from './routes/admin/conteudo'
import { Route as AdminHistoricoRouteImport } from './routes/admin/historico'
import { Route as AdminMateriaisRouteImport } from './routes/admin/materiais'
import { Route as AdminSaudeRouteImport } from './routes/admin/saude'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as GestaoRemuneracaoRouteImport } from './routes/gestao/remuneracao'
import { Route as GrupoSlugRouteImport } from './routes/grupo/$slug'
import { Route as MateriaisDeckRouteImport } from './routes/materiais/deck'
import { Route as MateriaisRepositorioRouteImport } from './routes/materiais/repositorio'
import { Route as NutricaoConcorrenciaRouteImport } from './routes/nutricao/concorrencia'
import { Route as NutricaoEmailsRouteImport } from './routes/nutricao/emails'
import { Route as PropostaIdRouteImport } from './routes/proposta.$id'
import { Route as RotinaCarteiraRouteImport } from './routes/rotina/carteira'
import { Route as RotinaReuniaoRouteImport } from './routes/rotina/reuniao'
import { Route as TreinamentoBlueprintRouteImport } from './routes/treinamento/blueprint'
import { Route as TreinamentoNpsCsatRouteImport } from './routes/treinamento/nps-csat'
import { Route as TreinamentoPerfilRouteImport } from './routes/treinamento/perfil'
import { Route as TreinamentoSimuladorRouteImport } from './routes/treinamento/simulador'
import { Route as TreinamentoSobreRouteImport } from './routes/treinamento/sobre'
import { Route as TreinamentoTecnicasRouteImport } from './routes/treinamento/tecnicas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinirSenhaRoute = DefinirSenhaRouteImport.update({
  id: '/definir-senha',
  path: '/definir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaPropostaRoute = NovaPropostaRouteImport.update({
  id: '/nova-proposta',
  path: '/nova-proposta',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostasRoute = PropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminConteudoRoute = AdminConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHistoricoRoute = AdminHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMateriaisRoute = AdminMateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSaudeRoute = AdminSaudeRouteImport.update({
  id: '/saude',
  path: '/saude',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRouteRoute,
} as any)
const GestaoRemuneracaoRoute = GestaoRemuneracaoRouteImport.update({
  id: '/gestao/remuneracao',
  path: '/gestao/remuneracao',
  getParentRoute: () => rootRouteImport,
} as any)
const GrupoSlugRoute = GrupoSlugRouteImport.update({
  id: '/grupo/$slug',
  path: '/grupo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaisDeckRoute = MateriaisDeckRouteImport.update({
  id: '/materiais/deck',
  path: '/materiais/deck',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaisRepositorioRoute = MateriaisRepositorioRouteImport.update({
  id: '/materiais/repositorio',
  path: '/materiais/repositorio',
  getParentRoute: () => rootRouteImport,
} as any)
const NutricaoConcorrenciaRoute = NutricaoConcorrenciaRouteImport.update({
  id: '/nutricao/concorrencia',
  path: '/nutricao/concorrencia',
  getParentRoute: () => rootRouteImport,
} as any)
const NutricaoEmailsRoute = NutricaoEmailsRouteImport.update({
  id: '/nutricao/emails',
  path: '/nutricao/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostaIdRoute = PropostaIdRouteImport.update({
  id: '/proposta/$id',
  path: '/proposta/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RotinaCarteiraRoute = RotinaCarteiraRouteImport.update({
  id: '/rotina/carteira',
  path: '/rotina/carteira',
  getParentRoute: () => rootRouteImport,
} as any)
const RotinaReuniaoRoute = RotinaReuniaoRouteImport.update({
  id: '/rotina/reuniao',
  path: '/rotina/reuniao',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinamentoBlueprintRoute = TreinamentoBlueprintRouteImport.update({
  id: '/treinamento/blueprint',
  path: '/treinamento/blueprint',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinamentoNpsCsatRoute = TreinamentoNpsCsatRouteImport.update({
  id: '/treinamento/nps-csat',
  path: '/treinamento/nps-csat',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinamentoPerfilRoute = TreinamentoPerfilRouteImport.update({
  id: '/treinamento/perfil',
  path: '/treinamento/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinamentoSimuladorRoute = TreinamentoSimuladorRouteImport.update({
  id: '/treinamento/simulador',
  path: '/treinamento/simulador',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinamentoSobreRoute = TreinamentoSobreRouteImport.update({
  id: '/treinamento/sobre',
  path: '/treinamento/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinamentoTecnicasRoute = TreinamentoTecnicasRouteImport.update({
  id: '/treinamento/tecnicas',
  path: '/treinamento/tecnicas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/conta': typeof ContaRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/historico': typeof HistoricoRoute
  '/nova-proposta': typeof NovaPropostaRoute
  '/propostas': typeof PropostasRoute
  '/timeline': typeof TimelineRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/historico': typeof AdminHistoricoRoute
  '/admin/materiais': typeof AdminMateriaisRoute
  '/admin/saude': typeof AdminSaudeRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/gestao/remuneracao': typeof GestaoRemuneracaoRoute
  '/grupo/$slug': typeof GrupoSlugRoute
  '/materiais/deck': typeof MateriaisDeckRoute
  '/materiais/repositorio': typeof MateriaisRepositorioRoute
  '/nutricao/concorrencia': typeof NutricaoConcorrenciaRoute
  '/nutricao/emails': typeof NutricaoEmailsRoute
  '/proposta/$id': typeof PropostaIdRoute
  '/rotina/carteira': typeof RotinaCarteiraRoute
  '/rotina/reuniao': typeof RotinaReuniaoRoute
  '/treinamento/blueprint': typeof TreinamentoBlueprintRoute
  '/treinamento/nps-csat': typeof TreinamentoNpsCsatRoute
  '/treinamento/perfil': typeof TreinamentoPerfilRoute
  '/treinamento/simulador': typeof TreinamentoSimuladorRoute
  '/treinamento/sobre': typeof TreinamentoSobreRoute
  '/treinamento/tecnicas': typeof TreinamentoTecnicasRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/conta': typeof ContaRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/historico': typeof HistoricoRoute
  '/nova-proposta': typeof NovaPropostaRoute
  '/propostas': typeof PropostasRoute
  '/timeline': typeof TimelineRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/historico': typeof AdminHistoricoRoute
  '/admin/materiais': typeof AdminMateriaisRoute
  '/admin/saude': typeof AdminSaudeRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/gestao/remuneracao': typeof GestaoRemuneracaoRoute
  '/grupo/$slug': typeof GrupoSlugRoute
  '/materiais/deck': typeof MateriaisDeckRoute
  '/materiais/repositorio': typeof MateriaisRepositorioRoute
  '/nutricao/concorrencia': typeof NutricaoConcorrenciaRoute
  '/nutricao/emails': typeof NutricaoEmailsRoute
  '/proposta/$id': typeof PropostaIdRoute
  '/rotina/carteira': typeof RotinaCarteiraRoute
  '/rotina/reuniao': typeof RotinaReuniaoRoute
  '/treinamento/blueprint': typeof TreinamentoBlueprintRoute
  '/treinamento/nps-csat': typeof TreinamentoNpsCsatRoute
  '/treinamento/perfil': typeof TreinamentoPerfilRoute
  '/treinamento/simulador': typeof TreinamentoSimuladorRoute
  '/treinamento/sobre': typeof TreinamentoSobreRoute
  '/treinamento/tecnicas': typeof TreinamentoTecnicasRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/conta': typeof ContaRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/historico': typeof HistoricoRoute
  '/nova-proposta': typeof NovaPropostaRoute
  '/propostas': typeof PropostasRoute
  '/timeline': typeof TimelineRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/historico': typeof AdminHistoricoRoute
  '/admin/materiais': typeof AdminMateriaisRoute
  '/admin/saude': typeof AdminSaudeRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/gestao/remuneracao': typeof GestaoRemuneracaoRoute
  '/grupo/$slug': typeof GrupoSlugRoute
  '/materiais/deck': typeof MateriaisDeckRoute
  '/materiais/repositorio': typeof MateriaisRepositorioRoute
  '/nutricao/concorrencia': typeof NutricaoConcorrenciaRoute
  '/nutricao/emails': typeof NutricaoEmailsRoute
  '/proposta/$id': typeof PropostaIdRoute
  '/rotina/carteira': typeof RotinaCarteiraRoute
  '/rotina/reuniao': typeof RotinaReuniaoRoute
  '/treinamento/blueprint': typeof TreinamentoBlueprintRoute
  '/treinamento/nps-csat': typeof TreinamentoNpsCsatRoute
  '/treinamento/perfil': typeof TreinamentoPerfilRoute
  '/treinamento/simulador': typeof TreinamentoSimuladorRoute
  '/treinamento/sobre': typeof TreinamentoSobreRoute
  '/treinamento/tecnicas': typeof TreinamentoTecnicasRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/conta'
    | '/definir-senha'
    | '/historico'
    | '/nova-proposta'
    | '/propostas'
    | '/timeline'
    | '/admin/conteudo'
    | '/admin/historico'
    | '/admin/materiais'
    | '/admin/saude'
    | '/admin/usuarios'
    | '/gestao/remuneracao'
    | '/grupo/$slug'
    | '/materiais/deck'
    | '/materiais/repositorio'
    | '/nutricao/concorrencia'
    | '/nutricao/emails'
    | '/proposta/$id'
    | '/rotina/carteira'
    | '/rotina/reuniao'
    | '/treinamento/blueprint'
    | '/treinamento/nps-csat'
    | '/treinamento/perfil'
    | '/treinamento/simulador'
    | '/treinamento/sobre'
    | '/treinamento/tecnicas'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/conta'
    | '/definir-senha'
    | '/historico'
    | '/nova-proposta'
    | '/propostas'
    | '/timeline'
    | '/admin/conteudo'
    | '/admin/historico'
    | '/admin/materiais'
    | '/admin/saude'
    | '/admin/usuarios'
    | '/gestao/remuneracao'
    | '/grupo/$slug'
    | '/materiais/deck'
    | '/materiais/repositorio'
    | '/nutricao/concorrencia'
    | '/nutricao/emails'
    | '/proposta/$id'
    | '/rotina/carteira'
    | '/rotina/reuniao'
    | '/treinamento/blueprint'
    | '/treinamento/nps-csat'
    | '/treinamento/perfil'
    | '/treinamento/simulador'
    | '/treinamento/sobre'
    | '/treinamento/tecnicas'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/conta'
    | '/definir-senha'
    | '/historico'
    | '/nova-proposta'
    | '/propostas'
    | '/timeline'
    | '/admin/conteudo'
    | '/admin/historico'
    | '/admin/materiais'
    | '/admin/saude'
    | '/admin/usuarios'
    | '/gestao/remuneracao'
    | '/grupo/$slug'
    | '/materiais/deck'
    | '/materiais/repositorio'
    | '/nutricao/concorrencia'
    | '/nutricao/emails'
    | '/proposta/$id'
    | '/rotina/carteira'
    | '/rotina/reuniao'
    | '/treinamento/blueprint'
    | '/treinamento/nps-csat'
    | '/treinamento/perfil'
    | '/treinamento/simulador'
    | '/treinamento/sobre'
    | '/treinamento/tecnicas'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContaRoute: typeof ContaRoute
  DefinirSenhaRoute: typeof DefinirSenhaRoute
  HistoricoRoute: typeof HistoricoRoute
  NovaPropostaRoute: typeof NovaPropostaRoute
  PropostasRoute: typeof PropostasRoute
  TimelineRoute: typeof TimelineRoute
  GestaoRemuneracaoRoute: typeof GestaoRemuneracaoRoute
  GrupoSlugRoute: typeof GrupoSlugRoute
  MateriaisDeckRoute: typeof MateriaisDeckRoute
  MateriaisRepositorioRoute: typeof MateriaisRepositorioRoute
  NutricaoConcorrenciaRoute: typeof NutricaoConcorrenciaRoute
  NutricaoEmailsRoute: typeof NutricaoEmailsRoute
  PropostaIdRoute: typeof PropostaIdRoute
  RotinaCarteiraRoute: typeof RotinaCarteiraRoute
  RotinaReuniaoRoute: typeof RotinaReuniaoRoute
  TreinamentoBlueprintRoute: typeof TreinamentoBlueprintRoute
  TreinamentoNpsCsatRoute: typeof TreinamentoNpsCsatRoute
  TreinamentoPerfilRoute: typeof TreinamentoPerfilRoute
  TreinamentoSimuladorRoute: typeof TreinamentoSimuladorRoute
  TreinamentoSobreRoute: typeof TreinamentoSobreRoute
  TreinamentoTecnicasRoute: typeof TreinamentoTecnicasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definir-senha': {
      id: '/definir-senha'
      path: '/definir-senha'
      fullPath: '/definir-senha'
      preLoaderRoute: typeof DefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-proposta': {
      id: '/nova-proposta'
      path: '/nova-proposta'
      fullPath: '/nova-proposta'
      preLoaderRoute: typeof NovaPropostaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propostas': {
      id: '/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof PropostasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/conteudo': {
      id: '/admin/conteudo'
      path: '/conteudo'
      fullPath: '/admin/conteudo'
      preLoaderRoute: typeof AdminConteudoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/historico': {
      id: '/admin/historico'
      path: '/historico'
      fullPath: '/admin/historico'
      preLoaderRoute: typeof AdminHistoricoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/materiais': {
      id: '/admin/materiais'
      path: '/materiais'
      fullPath: '/admin/materiais'
      preLoaderRoute: typeof AdminMateriaisRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/saude': {
      id: '/admin/saude'
      path: '/saude'
      fullPath: '/admin/saude'
      preLoaderRoute: typeof AdminSaudeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/gestao/remuneracao': {
      id: '/gestao/remuneracao'
      path: '/gestao/remuneracao'
      fullPath: '/gestao/remuneracao'
      preLoaderRoute: typeof GestaoRemuneracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupo/$slug': {
      id: '/grupo/$slug'
      path: '/grupo/$slug'
      fullPath: '/grupo/$slug'
      preLoaderRoute: typeof GrupoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiais/deck': {
      id: '/materiais/deck'
      path: '/materiais/deck'
      fullPath: '/materiais/deck'
      preLoaderRoute: typeof MateriaisDeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiais/repositorio': {
      id: '/materiais/repositorio'
      path: '/materiais/repositorio'
      fullPath: '/materiais/repositorio'
      preLoaderRoute: typeof MateriaisRepositorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutricao/concorrencia': {
      id: '/nutricao/concorrencia'
      path: '/nutricao/concorrencia'
      fullPath: '/nutricao/concorrencia'
      preLoaderRoute: typeof NutricaoConcorrenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutricao/emails': {
      id: '/nutricao/emails'
      path: '/nutricao/emails'
      fullPath: '/nutricao/emails'
      preLoaderRoute: typeof NutricaoEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposta/$id': {
      id: '/proposta/$id'
      path: '/proposta/$id'
      fullPath: '/proposta/$id'
      preLoaderRoute: typeof PropostaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotina/carteira': {
      id: '/rotina/carteira'
      path: '/rotina/carteira'
      fullPath: '/rotina/carteira'
      preLoaderRoute: typeof RotinaCarteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotina/reuniao': {
      id: '/rotina/reuniao'
      path: '/rotina/reuniao'
      fullPath: '/rotina/reuniao'
      preLoaderRoute: typeof RotinaReuniaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinamento/blueprint': {
      id: '/treinamento/blueprint'
      path: '/treinamento/blueprint'
      fullPath: '/treinamento/blueprint'
      preLoaderRoute: typeof TreinamentoBlueprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinamento/nps-csat': {
      id: '/treinamento/nps-csat'
      path: '/treinamento/nps-csat'
      fullPath: '/treinamento/nps-csat'
      preLoaderRoute: typeof TreinamentoNpsCsatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinamento/perfil': {
      id: '/treinamento/perfil'
      path: '/treinamento/perfil'
      fullPath: '/treinamento/perfil'
      preLoaderRoute: typeof TreinamentoPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinamento/simulador': {
      id: '/treinamento/simulador'
      path: '/treinamento/simulador'
      fullPath: '/treinamento/simulador'
      preLoaderRoute: typeof TreinamentoSimuladorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinamento/sobre': {
      id: '/treinamento/sobre'
      path: '/treinamento/sobre'
      fullPath: '/treinamento/sobre'
      preLoaderRoute: typeof TreinamentoSobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinamento/tecnicas': {
      id: '/treinamento/tecnicas'
      path: '/treinamento/tecnicas'
      fullPath: '/treinamento/tecnicas'
      preLoaderRoute: typeof TreinamentoTecnicasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminConteudoRoute: typeof AdminConteudoRoute
  AdminHistoricoRoute: typeof AdminHistoricoRoute
  AdminMateriaisRoute: typeof AdminMateriaisRoute
  AdminSaudeRoute: typeof AdminSaudeRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminConteudoRoute: AdminConteudoRoute,
  AdminHistoricoRoute: AdminHistoricoRoute,
  AdminMateriaisRoute: AdminMateriaisRoute,
  AdminSaudeRoute: AdminSaudeRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContaRoute: ContaRoute,
  DefinirSenhaRoute: DefinirSenhaRoute,
  HistoricoRoute: HistoricoRoute,
  NovaPropostaRoute: NovaPropostaRoute,
  PropostasRoute: PropostasRoute,
  TimelineRoute: TimelineRoute,
  GestaoRemuneracaoRoute: GestaoRemuneracaoRoute,
  GrupoSlugRoute: GrupoSlugRoute,
  MateriaisDeckRoute: MateriaisDeckRoute,
  MateriaisRepositorioRoute: MateriaisRepositorioRoute,
  NutricaoConcorrenciaRoute: NutricaoConcorrenciaRoute,
  NutricaoEmailsRoute: NutricaoEmailsRoute,
  PropostaIdRoute: PropostaIdRoute,
  RotinaCarteiraRoute: RotinaCarteiraRoute,
  RotinaReuniaoRoute: RotinaReuniaoRoute,
  TreinamentoBlueprintRoute: TreinamentoBlueprintRoute,
  TreinamentoNpsCsatRoute: TreinamentoNpsCsatRoute,
  TreinamentoPerfilRoute: TreinamentoPerfilRoute,
  TreinamentoSimuladorRoute: TreinamentoSimuladorRoute,
  TreinamentoSobreRoute: TreinamentoSobreRoute,
  TreinamentoTecnicasRoute: TreinamentoTecnicasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
